@startuml
skinparam packageStyle rectangle

package ポケモン集約 {
    object ポケモン {
        レベル
        性格
        HP
        攻撃
        防御
        特攻
        特防
        素早さ
    }
    note left of ポケモン
        HP～素早さは実値
        レベルは0~100まで
        性格は、アップとダウンのステータスから判定
        アップとダウンがなければ"がんばりや"で固定
    end note
    note top of ポケモン
        個体値と努力推定方法
        1: レベルと性格と種族値から、努力値を0として計算する。
        2: 問題なく入ったものは確定で、それ以外のものを個体値を31で仮定する。
        3: 2で仮で31にしたものから、努力値を計算する。
    end note
    object 種族値 {
        ポケモン（種類）
        HP
        攻撃
        防御
        特攻
        特防
        素早さ
    }
    note bottom of 種族値
        ポケモンの種類からリストから種族値を取得する。
    end note
    object 個体値 {
        HP
        攻撃
        防御
        特攻
        特防
        素早さ
    }
    note bottom of 個体値
        すべて0~31までの数字
    end note
    object 努力値 {
        HP
        攻撃
        防御
        特攻
        特防
        素早さ
    }
    note bottom of 努力値
        すべて0~255までの値
    end note
    ポケモン "1" o-- "1" 種族値
    ポケモン "1" *-- "0..1" 個体値
    ポケモン "1" *-- "0..1" 努力値
}


package Twitter集約 {
    object TwitterAccount {
        ユーザID
        パスワード
        タイムライン?
    }
    note right of TwitterAccount
        アカウントのタイムラインから、
        つぶやきを取得する
    end note
    object つぶやき {
        ツイートID？
        日時
        メッセージ
    }
    note top of つぶやき
        メッセージにポケモン剣盾のハッシュタグがあれば
        添付ファイルの画像をポケモンスクショ画像として扱う
    end note
    object 添付ファイル{
        ポケモンスクショ画像
    }
    note bottom of 添付ファイル
        ポケモンスクショ画像がステータス画面か判定する。
        判定した場合以下を読み込みポケモンをEntityを作成
        ・ポケモンの種類
        ・レベル
        ・性格
        ・HPなどのステータス
    end note
    object リプライ {
        リプライ先ID?
        ユーザID？
        メッセージ
    }
    note bottom of リプライ
        推定したポケモンの
        個体値と努力値をメッセージに入れる
        添付ファイルのついているつぶやきにリプライする。
    end note
    つぶやき "1" *-- "0..n" 添付ファイル
}
添付ファイル  -->  ポケモン

TwitterAccount "1" *-- "0..n" つぶやき
TwitterAccount  --  リプライ
ポケモン  --> リプライ
つぶやき "1" *-- "0..1" リプライ

@enduml